### PR TITLE
Support StrictRedis

### PR DESCRIPTION
**Pull request by thieman**
@tleach @inlinestyle

### CODE REVIEW

**Comment by inlinestyle** [comment]
Might be cleaner to just abstract this into `zadd_bridge` function, but seems legit otherwise.

**Comment by tleach** [comment]
Not sure what the backstory is here. Let's discuss on saturday...

**Comment by inlinestyle** [comment]
Looks good to me.

**Comment by inlinestyle** [comment]
that which is ZADD may never die

**Comment by inlinestyle** [comment]
yeah still seems ok

**Pull request merged**
